name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Unzip project
        run: unzip secure_diary_basic.zip -d secure_diary_basic

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build debug APK
        run: gradle assembleDebug --no-daemon
        working-directory: secure_diary_basic

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: secure_diary_basic/app/build/outputs/apk/debug/app-debug.apk
