name: Android CI - Build APK from ZIP

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Unzip project
        run: |
          unzip secure_diary_basic.zip -d project

      - name: Find project path
        id: findpath
        run: |
          echo "PROJECT_DIR=$(find project -name gradlew -exec dirname {} \;)" >> $GITHUB_ENV

      - name: Make gradlew executable
        run: chmod +x ${{ env.PROJECT_DIR }}/gradlew

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build debug APK
        run: ${{ env.PROJECT_DIR }}/gradlew assembleDebug --no-daemon
        working-directory: ${{ env.PROJECT_DIR }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: secure-diary-apk
          path: ${{ env.PROJECT_DIR }}/app/build/outputs/apk/debug/*.apk
