name: Android CI - Build APK (no wrapper)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Unzip project
        run: unzip secure_diary_basic.zip -d project

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build debug APK
        run: gradle assembleDebug --no-daemon
        working-directory: secure_diary_basic

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: secure-diary-apk
          path: secure_diary_basic/app/build/outputs/apk/debug/*.apk
